services:
  nginx:
    image: nginx:latest
    container_name: intranet-nginx
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./generate-nginx.sh:/generate-nginx.sh:ro
      - app_data:/var/www:ro
    depends_on:
      - app
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    command: >
      /bin/bash -c "
        envsubst '\$APP_DOMAIN' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'
      "
    networks:
      - intranet-net


  db:
    image: mariadb:10.11
    container_name: intranet-db
    ports:
      - "3307:3306"    
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MARIADB_DATABASE: '${DB_DATABASE:-intranet}'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - intranet-net


  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: intranet-app
    container_name: intranet-app
    restart: always
    expose: 
      - "9000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: intranet-db
      DB_PORT: 3306
      DB_DATABASE: intranet
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - intranet-net
    volumes:
      - app_data:/var/www


volumes:
  db_data:
    driver: local
  app_data:
    driver: local

networks:
  intranet-net:
    name: intranet-net
    driver: bridge