services:
  nginx:
    profiles:
      - production
    image: nginx:latest
    container_name: intranet-nginx
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./generate-nginx.sh:/generate-nginx.sh:ro
      - app_data:/var/www:ro
    depends_on:
      - app
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    command: >
      /bin/bash -c "
        envsubst '\$APP_DOMAIN' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'
      "
    networks:
      - intranet-net

  db:
    image: mariadb:10.11
    container_name: intranet-db
    ports:
      - "3307:3306"    
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MARIADB_DATABASE: '${DB_DATABASE:-intranet}'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - intranet-net

  app:
    profiles:
      - production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: intranet-app
    container_name: intranet-app
    restart: always
    expose: 
      - "9000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: intranet-db
      DB_PORT: 3306
      DB_DATABASE: intranet
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - intranet-net
    volumes:
      - app_data:/var/www

  app-dev:
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: intranet-app-dev
    container_name: intranet-app-dev
    restart: always
    ports:
      - "8000:8000"  # Laravel dev server
      - "5173:5173"  # Vite dev server
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: intranet-db
      DB_PORT: 3306
      DB_DATABASE: intranet
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - intranet-net
    volumes:
      - .:/var/www
      - /var/www/node_modules
      - /var/www/vendor
    develop:
      watch:
        - action: sync
          path: ./app
          target: /var/www/app
        - action: sync
          path: ./config
          target: /var/www/config
        - action: sync
          path: ./database
          target: /var/www/database
        - action: sync
          path: ./resources
          target: /var/www/resources
        - action: sync
          path: ./routes
          target: /var/www/routes
        - action: rebuild
          path: package.json
        - action: rebuild
          path: composer.json

volumes:
  db_data:
    driver: local
  app_data:
    driver: local

networks:
  intranet-net:
    name: intranet-net
    driver: bridge