server {
    listen 80;
    server_name intranet.hofstetterlab.ovh;

    set $is_local 0;
    if ($remote_addr ~ ^192\.168\.1\.) {
        set $is_local 1;
    }

    if ($is_local = 0) {
        return 301 https://$host$request_uri;
    }

    root /var/www/public;
    index index.html index.php;
    charset utf-8;

    # Routes Laravel + React
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }


    location ~* ^/build/assets/.*\.(css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|eot|otf|ttc|json)$ {
        root /var/www/public;
        try_files $uri =404;
        expires max;
        access_log off;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept' always;

    }


    # Exécution des scripts PHP
    location ~ \.php(?:$|/) {
        fastcgi_read_timeout 120;
        fastcgi_max_temp_file_size 0;
        fastcgi_buffer_size 4k;
        fastcgi_buffers 64 4k;
        send_timeout 120;
        fastcgi_pass intranet-app:9000;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        include fastcgi_params;
        try_files $fastcgi_script_name =404;


    }
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy no-referrer-when-downgrade;

    add_header Content-Security-Policy 'upgrade-insecure-requests' always;
}
